// Code generated by "stringer -type argType argument.go"; DO NOT EDIT.

package argument

import "strconv"

const _argType_name = "IntFloatStringBool"

var _argType_index = [...]uint8{0, 3, 8, 14, 18}

func (i argType) String() string {
	if i < 0 || i >= argType(len(_argType_index)-1) {
		return "argType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _argType_name[_argType_index[i]:_argType_index[i+1]]
}
